"""Shared, read-only C# audit scope and strict input/output helpers (Python 3.10+)."""

import argparse
import codecs
import json
import os
import re
import sys
import tempfile
from pathlib import Path


GENERATED_DIRS = {"bin", "obj", ".git", ".svn", ".hg", ".vs"}
GENERATED_SUFFIXES = (".g.cs", ".g.i.cs", ".generated.cs", ".designer.cs")


def read_source(path: Path, encoding: str = "auto") -> str:
    """Decode strictly; auto means BOM-aware UTF-8/16/32, otherwise UTF-8."""
    try:
        data = path.read_bytes()
        selected = encoding
        if encoding == "auto":
            if data.startswith((codecs.BOM_UTF32_LE, codecs.BOM_UTF32_BE)):
                selected = "utf-32"
            elif data.startswith((codecs.BOM_UTF16_LE, codecs.BOM_UTF16_BE)):
                selected = "utf-16"
            else:
                selected = "utf-8-sig"
        return data.decode(selected, errors="strict")
    except (OSError, UnicodeError, LookupError) as error:
        raise ValueError(f"Cannot read {path} ({encoding}): {error}") from error


def _generated_name(path: Path) -> bool:
    return (any(part.casefold() in GENERATED_DIRS for part in path.parts)
            or path.name.casefold().endswith(GENERATED_SUFFIXES))


def resolve_cs_files(scope: Path, include_from: Path | None = None,
                     include_generated: bool = False,
                     encoding: str = "auto") -> list[Path]:
    """A manifest restricts scope; its relative paths use the manifest directory."""
    scope = scope.resolve(strict=True)
    if scope.is_file() and scope.suffix.casefold() != ".cs":
        raise ValueError("--scope must be a .cs file or directory; project/solution "
                         "membership is not inferred. Supply an exact directory/file "
                         "scope and, if needed, a verified --include-from manifest")
    if not scope.is_file() and not scope.is_dir():
        raise ValueError(f"Invalid scope: {scope}")

    def validate(path: Path, origin: str) -> Path:
        resolved = path.resolve(strict=True)
        if not resolved.is_file() or resolved.suffix.casefold() != ".cs":
            raise ValueError(f"{origin}: not a .cs file: {path}")
        if (scope.is_file() and resolved != scope) or (
                scope.is_dir() and not resolved.is_relative_to(scope)):
            raise ValueError(f"{origin}: file is outside --scope: {path}")
        return resolved

    if include_from is not None:
        manifest = include_from.resolve(strict=True)
        files = set()
        for number, line in enumerate(read_source(manifest).splitlines(), 1):
            value = line.strip()
            if not value or value.startswith("#"):
                continue
            path = Path(value)
            if not path.is_absolute():
                path = manifest.parent / path
            try:
                files.add(validate(path, f"{manifest}:{number}"))
            except (OSError, ValueError) as error:
                raise ValueError(f"Invalid manifest entry {manifest}:{number}: {error}") from error
    elif scope.is_file():
        files = {scope}
    else:
        files = set()

        def fail(error: OSError) -> None:
            raise error

        for directory, children, names in os.walk(scope, onerror=fail, followlinks=False):
            children[:] = sorted(name for name in children if include_generated
                                 or name.casefold() not in GENERATED_DIRS)
            for name in sorted(names):
                if name.casefold().endswith(".cs"):
                    path = Path(directory) / name
                    if include_generated or not _generated_name(path):
                        files.add(validate(path, "directory scan"))

    result = []
    for path in sorted(files, key=lambda value: (str(value).casefold(), str(value))):
        if not include_generated and _generated_name(path):
            continue
        text = read_source(path, encoding)
        if not include_generated and re.search(
                r"^\s*(?://|/\*|\*)\s*<auto-generated\b",
                "\n".join(text.splitlines()[:20]), re.IGNORECASE | re.MULTILINE):
            continue
        result.append(path)
    return result


def add_scan_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--scope", required=True, help="Exact .cs file or directory")
    parser.add_argument("--include-from", help="UTF manifest: one .cs path per line, "
                        "relative to the manifest's directory; # comments allowed")
    parser.add_argument("--include-generated", action="store_true",
                        help="Include generated paths and auto-generated file headers")
    parser.add_argument("--encoding", default="auto",
                        help="Source encoding (default: BOM-aware auto, otherwise strict UTF-8)")
    parser.add_argument("--output", help="JSON report path, or - for JSON-only stdout without "
                        "a report file; default is a unique temporary directory")
    parser.add_argument("--quiet", action="store_true", help="Print only the report path; "
                        "--output - always prints JSON")
    parser.add_argument("--jobs", type=int, default=1, help="Parallel workers (positive integer)")


def write_report(value: dict, output: str | None, name: str) -> Path | None:
    """Serialize a complete report; file mode publishes it atomically."""
    if output == "-":
        sys.stdout.write(json.dumps(value, ensure_ascii=False, indent=2) + "\n")
        return None
    path = (Path(output).resolve() if output else
            Path(tempfile.mkdtemp(prefix="format-csharp-")) / name)
    if path.suffix.casefold() != ".json":
        raise ValueError("--output must have a .json extension")
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=path.parent,
                                         prefix=".audit-", suffix=".tmp", delete=False) as stream:
            temporary = Path(stream.name)
            json.dump(value, stream, ensure_ascii=False, indent=2)
            stream.write("\n")
        os.replace(temporary, path)
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()
    return path
